'use strict';
/* Topic workspace: all personal notes stay in this browser. */
const DM = window.DEPUTY_MATERIALS;
const MS = {tab:'2',year:'2026',budgetQuery:'',page:0,agenda:'all',agendaQuery:'',cultureQuery:'',culturePlace:'all',healthQuery:'',control:'all'};
let personal = {read:[],saved:[],notes:{},controls:{}};
try {const p=JSON.parse(localStorage.getItem('deputat-materials-v1')||'null'); if(p&&Array.isArray(p.read)&&Array.isArray(p.saved)&&p.notes&&p.controls) personal=p;} catch {}
MaterialStatus.migrate(personal);
function readAction(id){const read=MaterialStatus.isRead(personal,id);return `<div data-material-status="${esc(id)}" class="material-read-state ${read?'is-read':'is-new'}"><span class="material-read-badge" role="status">${MaterialStatus.state(personal,id)}</span><button class="secondary-button" data-material-read="${esc(id)}" aria-pressed="${read}">${read?'✓ Прочитано · снять отметку':'Отметить прочитанным'}</button></div>`;}
function refreshMaterialStatus(){for(const el of document.querySelectorAll('[data-material-status]')){const id=el.dataset.materialStatus,read=MaterialStatus.isRead(personal,id);el.classList.toggle('is-read',read);el.classList.toggle('is-new',!read);el.querySelector('[role="status"]').textContent=MaterialStatus.state(personal,id);const button=el.querySelector('button');button.setAttribute('aria-pressed',String(read));button.textContent=read?'✓ Прочитано · снять отметку':'Отметить прочитанным';}}
document.addEventListener('material-status-change',refreshMaterialStatus);
function materialSectionStatus(route){const id='collection:'+route;return MaterialStatus.catalog.has(id)?readAction(id):'';}
function publicNews(){return `<section class="card material-section"><h2>Публичные муниципальные новости</h2><p class="material-meta">Проверенные публикации с датой и ссылкой на источник. Чтение отмечается кнопкой; открытие страницы отметку не снимает.</p>${(window.PUBLIC_MUNICIPAL_NEWS||[]).map(n=>`<article class="material-news"><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><p class="material-meta">Опубликовано: ${dateRU(n.publishedAt)} · Обновлено: ${dateRU(n.updatedAt)}</p><a class="text-button" href="${esc(n.source.url)}" target="_blank" rel="noopener noreferrer">${esc(n.source.name)} ↗</a>${readAction(n.id)}</article>`).join('')||empty('Проверенных публичных новостей пока нет. Подборка ниже — архив материалов со своими датами. Не является текущей лентой новостей.')}</section>`;}
const rub = n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
const mln = n=>rub(n/1e6)+' млн ₽';
const dateRU = d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Krasnoyarsk'}).format(new Date(d+'T12:00:00+07:00'));
const note = (s,warning=false)=>`<div class="material-notice ${warning?'warning':''}">${esc(s)}</div>`;
const sourceLine=s=>`<p class="material-source">Источник: ${esc(s)}</p>`;
const empty=s=>`<div class="material-empty">${esc(s)}</div>`;
function savePersonal(){try{localStorage.setItem('deputat-materials-v1',JSON.stringify(personal));return true;}catch{toast('Хранилище недоступно: изменения сохранятся только до закрытия страницы. Скачай памятку.');return false;}}
function mstat(value,label,sub=''){return `<div class="material-stat"><strong>${value}</strong><span>${label}</span>${sub?`<small>${sub}</small>`:''}</div>`;}
function disclosure(title,body,open=false){return `<details class="material-details" ${open?'open':''}><summary>${esc(title)}</summary><div class="material-detail-body">${body}</div></details>`;}
function materialHero(){return `<a href="#materials" class="material-banner"><div><span class="eyebrow">МАТЕРИАЛЫ СКУРИХИНА · 1 ОКТЯБРЯ</span><h2>Из писем — в рабочий кабинет</h2><p>Бюджет, 74 вопроса повесток, обстановка и работа на территории.</p></div><span class="material-banner-arrow">↗</span></a>`;}
function materials(){return `${heading('РАБОЧАЯ ПОДБОРКА','Материалы Скурихина','Содержание писем разложено по темам и связано с инструментами подготовки.')}
${publicNews()}
<div class="material-stats">${mstat('18','вложений обработано','из 9 сохранённых писем')}${mstat('74','вопроса повесток','5 заседаний комиссий и Совета')}${mstat('3 833','строки бюджетных таблиц','6 приложений проекта')}</div>
${note('Подборка сохранена 1 октября 2026 года, сайт подготовлен 2 октября. Новые письма автоматически не подгружаются. Проекты, планы и старые сводки не подтверждают действующие решения или сегодняшнюю обстановку.')}
<div class="material-grid">${[['budget','01','Бюджет без папок','Сравни редакции и годы, найди расходы по программе или учреждению.','7,304 млрд ₽ · доходы проекта'],['agendas','02','Повестки и подготовка','Все вопросы, докладчики, отметки изученного и личные заметки.','Май — июль 2026'],['situation','03','Обстановка в округе','Пожары, дороги, вода, ЖКХ и тематический разбор краевого прогноза.','Срез на 1 октября'],['territory','04','Территории и события','33 мероприятия и работы: поиск по населённому пункту, месту и теме.','План 22–28 июня'],['initiatives','05','Инициативы и информирование','Поддержка учителей и восемь тем для информирования жителей.','Август — сентябрь 2026'],['preparation','06','Моя подготовка','Выбранные вопросы, заметки и контроль уточнений в одном месте.','Сохраняется на устройстве']].map(([route,n,title,desc,tag])=>`<a class="material-tile" href="#${route}"><span class="material-index">${n} <span>↗</span></span><h2>${title}</h2><p>${desc}</p><small>${tag}</small></a>`).join('')}</div>
<section class="card material-section"><h2>Требует внимания</h2><div class="material-grid">${DM.controls.slice(0,4).map(c=>`<a href="#preparation" class="material-alert"><h3>${esc(c.title)}</h3><p>${esc(c.fact)}</p></a>`).join('')}</div></section>
${disclosure('Что перенесено из каждого письма',`<div class="material-coverage">${DM.sources.map(s=>{const r=sourceRoute(s.title);return `<div><span>${esc(s.subject)}</span><strong>${esc(s.title)}</strong><a href="#${r}">Перейти к содержанию ↗</a></div>`;}).join('')}</div><p>Переписка, личные телефоны, подписи и сведения об отдельных пострадавших не опубликованы. В медицинских материалах использовано тематическое изложение с уточнениями. Оригиналы сохранены в проекте.</p>`)}`;}
function sourceRoute(t){if(/Повестка|ГРАФИК/.test(t))return 'agendas';if(/Решение|записка|обоснование|Заключение|Scan/.test(t))return 'budget';if(/22-28/.test(t))return 'territory';if(/прогноз|сводка/.test(t))return 'situation';return 'initiatives';}
function budget(){const values={'2026':[7303836519.03,7413893744.34,110057225.31],'2027':[6255535802.13,6255535802.13,0],'2028':[5802164014.34,5802164014.34,0]}[MS.year];return `${heading('ФИНАНСЫ ОКРУГА','Бюджет: понять и проверить','Июньский проект корректировки и отдельный отчёт об исполнении на 1 апреля.')}
${note('Это проект, поступивший в июне 2026 года, с незаполненными датой и номером. Действующая редакция бюджета на октябрь по этой подборке не установлена.',true)}
<div class="material-toolbar"><div class="segmented" role="group" aria-label="Год бюджета">${['2026','2027','2028'].map(y=>`<button data-m-year="${y}" class="${MS.year===y?'active':''}" aria-pressed="${MS.year===y}">${y}</button>`).join('')}</div><span class="material-meta">Рубли · значения проекта</span></div>
<div class="material-stats">${mstat(mln(values[0]),'Доходы',MS.year==='2026'?'+131,293 млн ₽ к редакции 22 апреля':'Плановый период')}${mstat(mln(values[1]),'Расходы',MS.year==='2026'?'+131,293 млн ₽ к редакции 22 апреля':'Плановый период')}${mstat(mln(values[2]),'Дефицит','Разница расходов и доходов')}</div>
${MS.year==='2027'?note('В обосновании ошибочно указано увеличение на 71,397 млн ₽. Пояснительная записка и КСП указывают уменьшение: −80,196 млн на переселение +8,799 млн на дополнительное образование.',true):''}
<section class="card material-section"><h2>2026: было → предлагается</h2><div class="material-table-scroll" tabindex="0"><table class="material-table"><thead><tr><th>Показатель</th><th>Редакция 22.04.2026, ₽</th><th>Июньский проект, ₽</th><th>Изменение, ₽</th></tr></thead><tbody><tr><td>Доходы</td><td>7 172 543 716,12</td><td>7 303 836 519,03</td><td>+131 292 802,91</td></tr><tr><td>Расходы</td><td>7 282 600 941,43</td><td>7 413 893 744,34</td><td>+131 292 802,91</td></tr><tr><td>Дефицит</td><td>110 057 225,31</td><td>110 057 225,31</td><td>0</td></tr></tbody></table></div>${sourceLine('Финансово-экономическое обоснование, заключение КСП от 22.06.2026.')}</section>
<section class="card material-section"><div class="section-heading"><h2>Куда меняется финансирование в 2026 году</h2><span class="material-meta">Сальдо по 7 программам</span></div>${DM.changes.map(([title,value,detail])=>`<details class="change-row"><summary><span>${esc(title)}</span><span class="${value<0?'negative':'positive'}">${value>0?'+':''}${mln(value)}</span></summary><div class="change-bar"><i class="${value<0?'negative':''}" style="width:${Math.abs(value)/89169287.88*100}%"></i></div><p>${esc(detail)}</p></details>`).join('')}${sourceLine('Заключение КСП от 22.06.2026 и пояснительная записка. В таблице показаны только изменения программ, не общий прирост бюджета.')}</section>
<section class="card material-section"><h2>Найти любую строку бюджета</h2><p class="material-meta">Приложения преобразованы в таблицы. Итоги и вложенные строки не складываются: они могут описывать одни и те же средства.</p><div class="material-toolbar"><label>Направление<select id="budget-table">${DM.tables.map(t=>`<option value="${t.id}" ${MS.tab===t.id?'selected':''}>${esc(t.title)}</option>`).join('')}</select></label><label class="grow">Поиск по названию или коду<input id="budget-query" type="search" value="${esc(MS.budgetQuery)}" placeholder="Школа, дороги, Чечеул, 0100…"></label></div><div id="budget-results">${budgetResults()}</div></section>
<section class="card material-section"><h2>Исполнение на 1 апреля 2026</h2><p class="material-meta">Отдельный отчёт, направленный администрацией 14 апреля. Другой период и другая редакция плана.</p><div class="material-stats">${mstat('19,8%','Доходы к годовому плану','1 426 949 471,93 ₽')}${mstat('18,7%','Расходы к годовому плану','1 355 396 921,17 ₽')}${mstat('71,553 млн ₽','Фактический профицит','за I квартал')}</div>${note('Кассовое исполнение зависит от сезонности и графиков закупок. Низкий процент в первом квартале сам по себе не означает срыв работ.')}
<div class="material-toolbar"><label class="grow">Поиск в отчёте на 1 апреля<input id="q1-query" type="search" placeholder="Дорожное хозяйство, образование…"></label><label>Таблица<select id="q1-table"><option value="programs">Муниципальные программы</option><option value="income">Доходы</option><option value="expenses">Расходы</option><option value="financing">Источники финансирования</option></select></label></div><div id="q1-results">${q1Results()}</div>
${disclosure('Численность и расходы на оплату труда',`<div class="material-stats">${mstat('274','Муниципальных служащих','58 211 тыс. ₽ фактических затрат')}${mstat('4 005','Работников учреждений','654 318 тыс. ₽ фактических затрат')}</div><p>Среднесписочная численность и фактические расходы на 1 апреля 2026 года. Единицы в исходнике: человек и тысячи рублей.</p>`)}${sourceLine('Сведения об исполнении бюджета на 01.04.2026, приложение к письму от 14.04.2026 № 1780.')}</section>
<section class="card material-section"><h2>Основания, детализация и замечания</h2>${disclosure('Что предлагает изменить проект',DM.budgetPreamble.map(p=>`<p>${esc(p)}</p>`).join(''))}${disclosure('Пояснения по доходам и программам',DM.explanation.map(s=>disclosure(s.title,s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join(''))).join(''))}${disclosure('Заключение КСП: разбор и предложения',note('Это оценка КСП на 22 июня. Устранение замечаний впоследствии не подтверждено.')+DM.ksp.map(p=>`<p>${esc(p)}</p>`).join(''))}${disclosure('Финансовое обоснование: содержание',note('Формулировка об увеличении показателей 2027 года расходится с пояснительной запиской и КСП. Содержание приведено с этой оговоркой.',true)+DM.financeNote.map(p=>`<p>${esc(p)}</p>`).join(''))}</section>`;}
function budgetResults(){const t=DM.tables.find(t=>t.id===MS.tab);const q=MS.budgetQuery.toLocaleLowerCase('ru');const rows=t.rows.map((r,i)=>({r,i})).filter(({r})=>r.some(x=>x)&&r.join(' ').toLocaleLowerCase('ru').includes(q));const pageSize=30;MS.page=Math.min(MS.page,Math.max(0,Math.ceil(rows.length/pageSize)-1));const visible=rows.slice(MS.page*pageSize,(MS.page+1)*pageSize);const count=t.headers.length;const cols=[...Array(count-3).keys(),count-3+(+MS.year-2026)];return `<div class="material-result-meta" role="status">Найдено ${rows.length} строк · ${esc(t.title)} · ${MS.year}</div>${visible.length?`<div class="material-table-scroll" tabindex="0" role="region" aria-label="Таблица бюджета"><table class="material-table"><thead><tr>${cols.map(c=>`<th scope="col">${esc(t.headers[c])}</th>`).join('')}<th scope="col">Сравнение</th></tr></thead><tbody>${visible.map(({r,i})=>`<tr>${cols.map(c=>`<td>${esc(r[c]||'—')}</td>`).join('')}<td><button class="secondary-button" data-budget-row="${i}">3 года</button></td></tr>`).join('')}</tbody></table></div><div class="material-pagination"><button class="secondary-button" data-budget-page="-1" ${MS.page===0?'disabled':''}>← Назад</button><span>${MS.page+1} / ${Math.ceil(rows.length/pageSize)}</span><button class="secondary-button" data-budget-page="1" ${(MS.page+1)*pageSize>=rows.length?'disabled':''}>Далее →</button></div>`:empty('Совпадений нет. Попробуй другое название или код.')}`;}
function q1Results(q='',key='programs'){const rows=(DM.q1?.[key]||[]).filter(r=>r[0].toLowerCase().includes(q.toLowerCase()));return rows.length?`<div class="material-table-scroll" tabindex="0" role="region" aria-label="Исполнение бюджета"><table class="material-table"><thead><tr><th scope="col">Показатель</th><th scope="col">Годовой план, ₽</th><th scope="col">Исполнено, ₽</th><th scope="col">По отчёту, %</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${rub(r[1])}</td><td>${rub(r[2])}</td><td>${r[3]===null?'—':rub(r[3])}</td></tr>`).join('')}</tbody></table></div>`:empty('Нет строк по этому запросу.');}
function agendas(){return `${heading('РАЗОБРАТЬ ВОПРОСЫ','Повестки','Май — июль 2026 · архив подготовки комиссий и Совета.')}${note('Дата и вопрос в повестке показывают запланированное рассмотрение. Итог голосования, принятие решения и его действующая редакция по этим файлам неизвестны.')}
<div class="material-toolbar"><label>Заседание<select id="agenda-select"><option value="all">Все 5 повесток</option>${DM.agendas.map(a=>`<option value="${a.id}" ${MS.agenda===a.id?'selected':''}>${dateRU(a.date)} · ${esc(a.title)}</option>`).join('')}</select></label><label class="grow">Поиск по вопросу или докладчику<input id="agenda-query" type="search" value="${esc(MS.agendaQuery)}" placeholder="Бюджет, инициативные проекты, Черепова…"></label></div>
<div class="material-toolbar"><span class="material-meta">${personal.read.length} изучено · ${personal.saved.length} в подготовке</span><a class="secondary-button" href="#preparation">Моя памятка ↗</a></div><div id="agenda-results">${agendaResults()}</div>
${disclosure('Полный майский график',`<div class="material-timeline">${[['13 мая, 14:00','Бюджетная комиссия'],['14 мая, 10:00','Комиссия по жизнеобеспечению'],['14 мая, 14:00','Социальная комиссия'],['21 мая, 10:00','11-е очередное заседание — повестки в подборке нет']].map(([d,t])=>`<div><b>${d}</b><span>${t}</span></div>`).join('')}</div>${sourceLine('ГРАФИК.doc · май 2026')}`)}
${disclosure('Как связаны июльские вопросы','<p>В совместной комиссии 7 июля и в повестке Совета 14 июля повторяются вопросы бюджета, ликвидационных балансов, оплаты труда, пенсий и процедур. В повестке Совета дополнительно указаны увековечение памяти и прекращение полномочий депутата.</p><p>Это последовательность рассмотрения по двум повесткам. Протоколов и результатов голосования в подборке нет.</p>')}`;}
function agendaResults(){const q=MS.agendaQuery.toLowerCase();let total=0;const body=DM.agendas.filter(a=>MS.agenda==='all'||a.id===MS.agenda).map(a=>{const items=a.items.filter(i=>(i.title+' '+i.speakers).toLowerCase().includes(q));total+=items.length;if(!items.length)return '';return `<section class="material-agenda-group"><div class="material-group-title"><span>${dateRU(a.date)} · ${a.time}</span><h2>${esc(a.title)}</h2><small>${items.length} вопросов</small></div>${a.id.includes('july')?note('В первом вопросе исходника стоит дата бюджетного акта 18.12.2026; вероятная опечатка. В самом бюджетном проекте указано 18.12.2025.'):''}<div class="material-agenda-list">${items.map(i=>agendaCard(i,a)).join('')}</div>${sourceLine(a.source)}</section>`;}).join('');return `<p class="material-result-meta" role="status">Найдено вопросов: ${total}</p>${body||empty('Вопросов по этому запросу нет.')}`;}
function agendaCard(i,a){return `<article class="agenda-item" id="item-${i.id}"><div class="agenda-item-top"><span class="material-index">${String(i.number).padStart(2,'0')}</span><h3>${esc(i.title)}</h3></div><div class="agenda-actions">${readAction(i.id)}<button data-read="${i.id}" aria-pressed="${personal.read.includes(i.id)}" class="secondary-button">${personal.read.includes(i.id)?'✓ Изучено':'Отметить изученным'}</button><button data-save-question="${i.id}" aria-pressed="${personal.saved.includes(i.id)}" class="secondary-button">${personal.saved.includes(i.id)?'✓ В моей подготовке':'+ В подготовку'}</button></div>${disclosure('Докладчики и моя заметка',`<p>${esc(i.speakers||'Докладчик не указан.')}</p><p class="material-meta">${esc(i.question)}</p><label>Мои вопросы к обсуждению<textarea data-question-note="${i.id}" rows="3" placeholder="Что уточнить, какие цифры сверить…">${esc(personal.notes[i.id]||'')}</textarea></label><p class="material-meta">Заметка сохраняется на этом устройстве, без отправки на сервер.</p>`)}</article>`;}
function situation(){return `${heading('СНИМОК ОБСТАНОВКИ','Округ: на что обратить внимание','По сводке ЕДДС на 08:00 1 октября и краевому прогнозу на 1 октября 2026.')}${note('Архивный срез. Это не мониторинг в реальном времени и не действующее оповещение.')}
<div class="material-stats">${mstat('0','ЧС в сводке','ЧС на контроле также не указаны')}${mstat('0','Аварий ТЭК и ЖКХ','по сводке на утро 1 октября')}${mstat('Открыты','Федеральные и местные дороги','во всех направлениях')}</div>
<div class="material-grid"><section class="card"><span class="eyebrow">ПОЖАРЫ С НАЧАЛА ГОДА</span><h2>Меньше всего. Больше в жилье.</h2>${[['Все пожары',277,368],['Жилой сектор',89,76],['Прочие',188,292],['Погибшие',4,1],['Травмированные',4,1]].map(([t,v,old])=>`<div class="material-comparison"><span>${t}</span><b>${v}<small> / ${old}</small></b><em>${v-old>0?'+':''}${v-old}</em></div>`).join('')}<p class="material-meta">2026 / сопоставимый период 2025 · по сводке.</p><a class="text-button" href="#preparation">Добавить внимание к профилактике →</a></section>
<section class="card"><span class="eyebrow">РЕКА КАН · ВОДОПОСТ КАНСК</span><div class="water-value">143 <small>см</small></div><meter min="0" max="370" value="143" aria-label="Уровень воды 143 сантиметра при критическом 370">143 из 370</meter><p>Критическая отметка — 370 см. В краевом прогнозе изменение за сутки: +10 см.</p><p class="material-meta">Уровень на 08:00 30 сентября. До критической отметки — 227 см; это арифметическая разница, не прогноз.</p></section></div>
<section class="card material-section"><h2>Другие показатели сводки</h2><div class="material-grid">${[['Режим работы','В сводке указан режим повышенной готовности; начало отопительного сезона — распоряжение № 719 от 17.09.2026.'],['Происшествия','Новых происшествий не указано; на контроле — одно. Индивидуальные обстоятельства пострадавшего не публикуются.'],['Патрули и спасатели','13 патрульных групп, 30 человек, 5 единиц техники. АСП: 3 выезда, 6 человек и 3 единицы техники.'],['ДТП','Одно ДТП, погибших и травмированных нет.'],['Погода','Фактически на 08:00: +5 °C. Прогноз в сводке: небольшие дожди, северный и северо-восточный ветер 2–7 м/с, днём +8…+13 °C.'],['Радиационный фон','0,08 мкЗв/ч; в сводке соответствует естественному фону.']].map(([t,p])=>`<div><h3>${t}</h3><p>${p}</p></div>`).join('')}</div>${sourceLine('Оперативная сводка ЕДДС Канского МО на 08:00 01.10.2026.')}</section>
<section class="card material-section"><h2>Что относится к Канскому округу в краевом прогнозе</h2><ul class="material-bullets"><li>Карантин по бешенству упомянут для Канского округа. Границы и актуальность ограничений нужно проверять отдельно.</li><li>Переувлажнение почвы: ГМО Канск с 16 сентября, АМП Красный Маяк с 18 сентября; в прогнозе явление продолжалось.</li><li>Для Канского округа указан I класс пожарной опасности.</li></ul><p class="material-meta">Остальные цифры ниже могут относиться ко всему Красноярскому краю — они не приписываются Канскому округу.</p></section>
<section class="card material-section"><h2>Краевой прогноз по темам</h2><p class="material-meta">Наблюдения, риски и рекомендации службам разделены на ${DM.forecast.length} раскрывающихся тем. Это содержание прогноза на 01.10.2026.</p>${DM.forecast.map(s=>disclosure(s.title,s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')+s.tables.map(rows=>`<div class="material-table-scroll" tabindex="0"><table class="material-table"><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`).join(''))).join('')}</section>`;}
function territory(){return `${heading('РАБОТА НА ТЕРРИТОРИИ','События и муниципальные объекты','План управления культуры на 22–28 июня 2026 года.')}${note('Это архивный план, а не подтверждение проведения мероприятий или завершения ремонта. В одном пункте исходника стоит 22 мая — расхождение сохранено.')}
<div class="material-toolbar"><label class="grow">Найти событие, объект или населённый пункт<input id="culture-query" type="search" value="${esc(MS.cultureQuery)}" placeholder="Чечеул, библиотека, благоустройство…"></label><label>Тип<select id="culture-type"><option value="all">Все мероприятия</option><option value="works" ${MS.culturePlace==='works'?'selected':''}>Ремонт и благоустройство</option><option value="events" ${MS.culturePlace==='events'?'selected':''}>Культурные события</option></select></label></div><div id="culture-results">${cultureResults()}</div>${sourceLine('План управления по культуре и туризму «22-28.06..doc». Прямые телефоны ответственных исключены из публичной страницы.')}`;}
function cultureResults(){const rows=DM.culture.filter(c=>{const work=/ремонт|благоустройств/i.test(c.title);return (MS.culturePlace==='all'||(MS.culturePlace==='works'?work:!work))&&(c.title+' '+c.place+' '+c.description).toLowerCase().includes(MS.cultureQuery.toLowerCase());});return `<p class="material-result-meta" role="status">Найдено: ${rows.length} из 33</p><div class="material-grid">${rows.map(c=>`<article class="material-event card"><span class="eyebrow">${esc(c.date)}</span><h2>${esc(c.title)}</h2>${readAction('culture-plan-2026-06-22:'+c.id)}<p class="material-place">${icon('pin')}${esc(c.place)}</p><p>${esc(c.description)}</p>${c.warning?note(c.warning,true):''}${disclosure('Ответственный по плану',`<p>${esc(c.responsible)}</p>`)}<button class="secondary-button" data-culture-save="${c.id}">В план уточнений +</button></article>`).join('')||empty('Совпадений нет.')}</div>`;}
function initiatives(){return `${heading('ИНИЦИАТИВЫ И ИНФОРМИРОВАНИЕ','От идеи — к предметным вопросам','Поддержка учителей и материалы для жителей из рассылки.')}
<section class="card teacher-card"><span class="eyebrow">ПИСЬМО КОМИТЕТА · 26 АВГУСТА 2026</span><h2>«Моя инициатива поддержки учителей»</h2><p>Комитет по образованию и культуре Законодательного Собрания края направил информацию о приёме предложений к общественной инициативе. Приложение описывает развитие дополнительных мер поддержки на муниципальном уровне, в том числе с привлечением спонсорской помощи.</p>${note('Это информационное предложение. Подборка не подтверждает финансирование, запуск в Канском округе или обязанность депутата участвовать.',true)}
<div class="material-timeline"><div><b>11 августа</b><span>Письмо Координационного совета с приложением.</span></div><div><b>26 августа</b><span>Пересылка информации комитетом Законодательного Собрания. В названии файла ошибочно указан июнь.</span></div><div><b>3 рабочих дня</b><span>Просьба организатора связаться после получения информации. Не установленная здесь юридическая обязанность и не рассчитанный срок для Ивана.</span></div></div>
${disclosure('Какие сведения ещё есть в приложении','<p>В письме указаны Указ № 498 от 20.07.2026 и публикация паспорта инициативы 27.07.2026. Существование, содержание и действующий статус этих оснований отдельно не подтверждены.</p><p>Организатор предлагает знакомиться с паспортом на ресурсах «Стратегии России» и «Проекты России», либо запросить его по электронной почте. Эти ресурсы не проверены и не представлены здесь как государственные порталы.</p><p>Рабочий следующий шаг — получить паспорт через аппарат Совета, уточнить бюджет, правовую схему и обязательства округа.</p>')}
<div class="material-question-box"><h3>Что выяснить до участия</h3><ul><li>Кто организатор и каковы полномочия участников?</li><li>Какие именно меры доступны учителям и по каким критериям?</li><li>Есть ли расходы округа, соглашения и обязательства перед спонсорами?</li><li>Как измеряется результат и кто отвечает за исполнение?</li></ul><button class="secondary-button" data-control-add="teachers">Добавить в подготовку</button></div>${sourceLine('Письмо от 26.08.2026 № 1868-4-32 и приложение к письму от 11.08.2026.')}</section>
<section class="material-section"><div class="section-heading"><h2>Информирование жителей</h2><span class="material-meta">8 тем · 2 рассылки Роспотребнадзора</span></div>${note('Тематическое изложение памяток для информирования, а не индивидуальные назначения. Медицинские формулировки сокращены и уточнены; сроки и противопоказания определяет врач.')}<label class="material-search">Поиск по темам<input id="health-query" type="search" value="${esc(MS.healthQuery)}" placeholder="Грипп, бешенство, прививки…"></label><div id="health-results">${healthResults()}</div></section>`;}
function healthResults(){const list=DM.health.filter(h=>(h.title+' '+h.summary).toLowerCase().includes(MS.healthQuery.toLowerCase()));return `<div class="material-grid">${list.map(h=>`<article class="card material-health"><span class="eyebrow">ДЛЯ ИНФОРМИРОВАНИЯ</span><h2>${esc(h.title)}</h2>${readAction('health:'+h.id)}<p>${esc(h.summary)}</p><ul>${h.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>${h.warning?note(h.warning,true):''}${sourceLine(h.source)}${h.link?`<a class="text-button" href="${esc(h.link)}" target="_blank" rel="noopener">Проверочный источник ↗</a>`:''}<button class="secondary-button" data-health-copy="${h.id}">Скопировать памятку</button></article>`).join('')||empty('Такой темы нет.')}</div>`;}
function preparation(){const saved=DM.agendas.flatMap(a=>a.items.map(i=>({i,a}))).filter(({i})=>personal.saved.includes(i.id));return `${heading('МОИ ВОПРОСЫ И ОТМЕТКИ','Подготовка','Выбери, что изучить и уточнить. Здесь нет отправки писем или официальных поручений.')}${note('Заметки и отметки хранятся в браузере этого устройства. Для резервной копии скачай памятку. Не записывай здесь персональные данные жителей.')}
<div class="material-toolbar"><span class="material-meta">${saved.length} вопросов выбрано · ${personal.read.length} изучено</span><button class="primary-button" data-export-brief>Скачать мою памятку</button></div>
<section class="card material-section"><h2>Проверить и уточнить</h2><div class="material-toolbar"><label>Показать<select id="control-filter"><option value="all">Все</option><option value="new" ${MS.control==='new'?'selected':''}>Не начато</option><option value="working" ${MS.control==='working'?'selected':''}>В работе</option><option value="done" ${MS.control==='done'?'selected':''}>Уточнено</option></select></label></div><div id="control-results">${controlResults()}</div></section>
<section class="material-section"><h2>Выбранные вопросы повесток</h2>${saved.length?saved.map(({i,a})=>`<p class="material-meta">${dateRU(a.date)} · ${esc(a.title)}</p>${agendaCard(i,a)}`).join(''):empty('Добавь вопросы кнопкой «В подготовку» в разделе «Повестки».')}<a class="text-button" href="#agendas">Перейти к повесткам →</a></section>
<section class="card material-section"><h2>Личный план работы</h2><label>Вопросы по территориям и другим материалам<textarea id="personal-plan" rows="7" placeholder="Объект, что уточнить, следующий шаг…">${esc(personal.notes.plan||'')}</textarea></label><p class="material-meta" id="note-save-status" role="status">Сохранение на устройстве по мере ввода.</p></section>`;}
function controlResults(){const list=DM.controls.filter(c=>MS.control==='all'||(personal.controls[c.id]||'new')===MS.control);return list.map(c=>`<article class="control-card"><div><h3>${esc(c.title)}</h3><p>${esc(c.fact)}</p><p class="material-next"><b>Следующий шаг:</b> ${esc(c.action)}</p><a class="text-button" href="#${c.route}">Открыть тему ↗</a></div><label>Моя отметка<select data-control-state="${c.id}">${[['new','Не начато'],['working','В работе'],['done','Уточнено']].map(([v,t])=>`<option value="${v}" ${(personal.controls[c.id]||'new')===v?'selected':''}>${t}</option>`).join('')}</select></label></article>`).join('')||empty('В этой группе пока нет вопросов.');}
function briefText(){const lines=['МОЯ ПОДГОТОВКА · КАНСКИЙ ОКРУГ','Содержание по подборке на 01.10.2026. Проекты и повестки не подтверждают принятые решения.',''];for(const c of DM.controls)lines.push(c.title+' — '+({'new':'Не начато','working':'В работе','done':'Уточнено'}[personal.controls[c.id]||'new']),c.fact,'Следующий шаг: '+c.action,'');for(const a of DM.agendas)for(const i of a.items)if(personal.saved.includes(i.id)||personal.notes[i.id])lines.push(dateRU(a.date)+' · '+a.title,'Вопрос '+i.number+': '+i.title,personal.read.includes(i.id)?'Изучено':'Не отмечено изученным',i.speakers,'Моя заметка: '+(personal.notes[i.id]||'—'),'');lines.push('ЛИЧНЫЙ ПЛАН',personal.notes.plan||'—');return lines.join('\n');}
async function copyMaterial(s){try{await navigator.clipboard.writeText(s);toast('Текст скопирован. Ничего не отправлено.');}catch{showMaterialDialog('Текст для копирования',`<textarea rows="12" readonly>${esc(s)}</textarea>`);}}
function showMaterialDialog(title,body){$('#dialog-label').textContent='МАТЕРИАЛЫ СКУРИХИНА';$('#dialog-body').innerHTML=`<h2>${esc(title)}</h2>${body}`;if(!$('#detail-dialog').open)$('#detail-dialog').showModal();}
function updateList(id,body){const el=document.getElementById(id);if(el)el.innerHTML=body;}
document.addEventListener('input',e=>{const t=e.target;if(t.id==='budget-query'){MS.budgetQuery=t.value;MS.page=0;updateList('budget-results',budgetResults());}if(t.id==='agenda-query'){MS.agendaQuery=t.value;updateList('agenda-results',agendaResults());}if(t.id==='culture-query'){MS.cultureQuery=t.value;updateList('culture-results',cultureResults());}if(t.id==='health-query'){MS.healthQuery=t.value;updateList('health-results',healthResults());}if(t.id==='q1-query')updateList('q1-results',q1Results(t.value,$('#q1-table').value));if(t.dataset.questionNote){personal.notes[t.dataset.questionNote]=t.value;savePersonal();}if(t.id==='personal-plan'){personal.notes.plan=t.value;const ok=savePersonal();$('#note-save-status').textContent=ok?'Сохранено на этом устройстве.':'Только в памяти страницы. Скачай памятку.';}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='budget-table'){MS.tab=t.value;MS.page=0;updateList('budget-results',budgetResults());}if(t.id==='q1-table')updateList('q1-results',q1Results($('#q1-query').value,t.value));if(t.id==='agenda-select'){MS.agenda=t.value;updateList('agenda-results',agendaResults());}if(t.id==='culture-type'){MS.culturePlace=t.value;updateList('culture-results',cultureResults());}if(t.id==='control-filter'){MS.control=t.value;updateList('control-results',controlResults());}if(t.dataset.controlState){personal.controls[t.dataset.controlState]=t.value;savePersonal();if(MS.control!=='all')updateList('control-results',controlResults());}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
if(d.mYear){MS.year=d.mYear;render();}
if(d.budgetPage){MS.page+=Number(d.budgetPage);updateList('budget-results',budgetResults());$('#budget-results').scrollIntoView({block:'start'});}
if(d.budgetRow!==undefined){const t=DM.tables.find(t=>t.id===MS.tab),r=t.rows[+d.budgetRow];showMaterialDialog('Одна строка · три года',`<p>${esc(r.slice(0,-3).filter(Boolean).join(' · '))}</p><div class="material-stats">${r.slice(-3).map((v,i)=>mstat(esc(v||'—'),String(2026+i),'рублей · проект')).join('')}</div>${sourceLine(t.title+' · Решение.docx, июньский проект.')}`);}
if(d.materialRead){const ok=MaterialStatus.toggle(personal,d.materialRead);refreshMaterialStatus();if(!ok)toast('Хранилище недоступно: отметка сохранится только до закрытия страницы.');}
if(d.read){const id=d.read;personal.read=personal.read.includes(id)?personal.read.filter(x=>x!==id):[...personal.read,id];savePersonal();b.setAttribute('aria-pressed',String(personal.read.includes(id)));b.textContent=personal.read.includes(id)?'✓ Изучено':'Отметить изученным';}
if(d.saveQuestion){const id=d.saveQuestion;personal.saved=personal.saved.includes(id)?personal.saved.filter(x=>x!==id):[...personal.saved,id];savePersonal();b.setAttribute('aria-pressed',String(personal.saved.includes(id)));b.textContent=personal.saved.includes(id)?'✓ В моей подготовке':'+ В подготовку';}
if(d.cultureSave){const c=DM.culture.find(c=>c.id===d.cultureSave);const text=c.title+' · '+c.place+'\nУточнить результат по плану: '+c.date+'\n';personal.notes.plan=(personal.notes.plan||'')+'\n'+text;savePersonal();toast('Добавлено в личный план в разделе «Подготовка».');}
if(d.controlAdd){personal.controls[d.controlAdd]='working';savePersonal();toast('Добавлено в работу в разделе «Подготовка».');}
if(d.healthCopy){const h=DM.health.find(h=>h.id===d.healthCopy);await copyMaterial([h.title,h.summary,...h.points,h.warning||'','Источник: '+h.source,h.link||'','Общие сведения; индивидуальные вопросы обсудите с врачом.'].filter(Boolean).join('\n\n'));}
if(d.exportBrief!==undefined){const url=URL.createObjectURL(new Blob([briefText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Моя подготовка — Канский округ.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Памятка подготовлена для скачивания.');}
});
window.MaterialViews={materials,budget,agendas,situation,territory,initiatives,preparation};
